name: the_man_who_sold_the_world
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/NIRVANA.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
